version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - 80:8000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=a46cd2ef79d790b69bd8
      - DRONE_GITHUB_SECRET=2ee96a072f7ccfaf094c9abe8039900c90df0884
      - DRONE_SECRET=my-secret

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://172.20.0.2:8000/ws/broker
      - DRONE_SECRET=my-secret
