# -*- mode: ruby -*-
# vim: set ft=ruby ts=2 et :

VAGRANTFILE_API_VERSION = "2"

# Tested with Vagrant version:
Vagrant.require_version ">= 1.7.2"

# Require YAML module
require 'yaml'

def fail_with_message(msg)
    fail Vagrant::Errors::VagrantError.new, msg
end

# Read YAML file with cluster details
config_file = 'config/cluster.yaml'
if File.exists?(config_file)
    cluster = YAML.load_file(config_file)
else
    fail_with_message "#{config_file} was not found."
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Disabling the default /vagrant share
  config.vm.synced_folder ".", "/vagrant", disabled: true

   ANSIBLE_RAW_SSH_ARGS = []

  cluster.each do |servers|
    host = servers['name']
    ANSIBLE_RAW_SSH_ARGS << "-o IdentityFile=.vagrant/machines/#{host}/libvirt/private_key"
  end

  i = 0
  cluster.each do |servers|
    # VM definition
    config.vm.define servers["name"] do |node|
      node.vm.box = servers["box"]
      node.vm.hostname = servers["name"]
      node.vm.network "private_network", ip: servers["ip"]
      node.vm.provider :libvirt do |domain|
        domain.uri = 'qemu+unix:///system'
        domain.driver = 'kvm'
        domain.memory = servers["mem"]
        domain.cpus = servers['cpu']
        domain.storage :file, :size => servers['aditional_disk']
      end
      i += 1
      if i == cluster.length
          node.vm.provision :ansible do |ansible|
            ansible.verbose = "v"
            ansible.inventory_path = "provisioning/inventory"
            ansible.raw_ssh_args = ANSIBLE_RAW_SSH_ARGS
            ansible.playbook = "provisioning/site.yml"
            ansible.limit = "all"
          end # provison
      end # if
    end # config
  end # cluster
end # vagrant
